kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: dz-collector-stag-cpu-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dz-collector-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: dz-collector-stag-cpu
      targetValue: 5
